"""Realistic browser user-agent strings for HTTP requests.

Loads UAs from kaos_web/data/user_agents.json, generated by
scripts/update_user_agents.py from microlinkhq/top-user-agents
(updated weekly from 300M+ real requests).

To refresh: uv run python scripts/update_user_agents.py
"""

from __future__ import annotations

import json
import random
from pathlib import Path
from urllib.parse import urlsplit

_DATA_FILE = Path(__file__).parent.parent / "data" / "user_agents.json"

# Load UA data at import time (fast — small JSON file)
_data: dict = {}
if _DATA_FILE.exists():
    _data = json.loads(_DATA_FILE.read_text())

DESKTOP_USER_AGENTS: list[str] = _data.get(
    "desktop",
    [
        # Fallback if data file missing
        (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/146.0.0.0 Safari/537.36"
        ),
        (
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/146.0.0.0 Safari/537.36"
        ),
        (
            "Mozilla/5.0 (X11; Linux x86_64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/146.0.0.0 Safari/537.36"
        ),
    ],
)

MOBILE_USER_AGENTS: list[str] = _data.get(
    "mobile",
    [
        (
            "Mozilla/5.0 (Linux; Android 14; Pixel 8) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/146.0.0.0 Mobile Safari/537.36"
        ),
    ],
)

ALL_USER_AGENTS: list[str] = DESKTOP_USER_AGENTS + MOBILE_USER_AGENTS

# KAOS bot UA (for when you want to identify as a bot)
KAOS_BOT_UA = "KAOS-Web/0.1 (+https://273ventures.com/kaos-web)"


def random_desktop_ua() -> str:
    """Return a random realistic desktop browser user-agent."""
    return random.choice(DESKTOP_USER_AGENTS)


def random_mobile_ua() -> str:
    """Return a random realistic mobile browser user-agent."""
    return random.choice(MOBILE_USER_AGENTS)


def random_ua() -> str:
    """Return a random realistic browser user-agent (desktop or mobile)."""
    return random.choice(ALL_USER_AGENTS)


# Hosts that block randomized Chrome desktop UAs but accept honest
# bot identifiers (`KAOS_BOT_UA`). Verified empirically 2026-05-22:
# SEC.gov returns 403 for Chrome UAs even with realistic Accept/
# Accept-Language headers, but returns 200 for bot-style UAs that
# identify the operator. This matches the SEC's published guidance
# that automated requests must include a descriptive User-Agent.
#
# Match is suffix-based: ``sec.gov`` matches ``www.sec.gov`` and
# ``efts.sec.gov`` but not ``not-sec.gov`` (a leading-dot boundary
# is enforced; the bare host is also accepted as an exact match).
BOT_FRIENDLY_HOSTS: frozenset[str] = frozenset(
    {
        # US federal government anti-bot domains
        "sec.gov",  # SEC EDGAR + press releases
        "govinfo.gov",  # GPO
        "federalregister.gov",
        "ecfr.gov",
        "congress.gov",
        "uscourts.gov",  # PACER + court opinions
        "courtlistener.com",  # legal research (Free Law Project)
        "irs.gov",
        "fcc.gov",
        "ftc.gov",
        "doj.gov",
        "treasury.gov",
        "data.gov",
        # Non-US gov bots that prefer honest identifiers
        "europa.eu",  # EU institutions
    }
)


def _host_matches_bot_friendly(host: str) -> bool:
    """True iff ``host`` ends with a bot-friendly suffix.

    Implements suffix match with a domain-boundary check so
    ``not-sec.gov`` does not falsely match ``sec.gov``.
    """
    h = (host or "").lower().strip()
    if not h:
        return False
    return any(h == suffix or h.endswith("." + suffix) for suffix in BOT_FRIENDLY_HOSTS)


def pick_user_agent_for_url(url: str, *, default_random: bool = True) -> str:
    """Pick the right User-Agent for ``url``.

    Hosts in :data:`BOT_FRIENDLY_HOSTS` (SEC.gov, govinfo, eCFR, …)
    get :data:`KAOS_BOT_UA` — they reject randomized Chrome UAs but
    accept honest bot identifiers.

    All other hosts get a random realistic desktop UA when
    ``default_random=True``; otherwise :data:`KAOS_BOT_UA`. This
    preserves the existing "look like a browser" strategy for
    consumer sites that block obvious bots while fixing the
    inverted-incentive failure on government domains.
    """
    try:
        host = urlsplit(url).hostname or ""
    except (ValueError, AttributeError):
        host = ""
    if _host_matches_bot_friendly(host):
        return KAOS_BOT_UA
    if default_random:
        return random_desktop_ua()
    return KAOS_BOT_UA
